write.csv(file=paste0("RIzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),read.csv("https://static.dwcdn.net/data/59UZY.csv"))

write.csv(file=paste0("NMzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://e7p503ngy5.execute-api.us-west-2.amazonaws.com/prod/GetPublicZipsData")[["data"]])

write.csv(file=paste0("LAmuni",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services5.arcgis.com/7nsPwEMP38bSkCjy/ArcGIS/rest/services/COVID19_by_Neighborhood/FeatureServer/0/query?where=FID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("CTmuni",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),read.csv("https://stateofhealth.ct.gov/content/covidFiles/town_result.csv"))

write.csv(file=paste0("DEzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services1.arcgis.com/PlCPCPzGOwulHUHo/ArcGIS/rest/services/DEMA_COVID_ByZip/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("NCzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/iFBq2AW9XO0jYYF7/ArcGIS/rest/services/Covid19byZIPnew/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("AZzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services1.arcgis.com/mpVYz37anSdrK4d8/ArcGIS/rest/services/CVD_ZIPS_FORWEBMAP/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("NassauNYmuni",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services1.arcgis.com/rsOafHhKLHpnpr4t/ArcGIS/rest/services/COVID_Map2_view5/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("BergenNJmuni",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://healthgis.co.bergen.nj.us/arcgis/rest/services/Hosted/BergenCountyMunicipalities_cent/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=*&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=xyFootprint&resultOffset=&resultRecordCount=&returnTrueCurves=false&returnCentroid=false&sqlFormat=none&resultType=&f=pjson")[["features"]][["attributes"]])

write.csv(file=paste0("BergenNJmunib",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),BergenNJmunib051620<-jsonlite::fromJSON("https://healthgis.co.bergen.nj.us/arcgis/rest/services/Hosted/2020_Shared_Services_Contracts/FeatureServer/0/query?where=FID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=*&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=xyFootprint&resultOffset=&resultRecordCount=&returnTrueCurves=false&returnCentroid=false&sqlFormat=none&resultType=&f=pjson")[["features"]][["attributes"]])

write.csv(file=paste0("HoustonTXzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/su8ic9KbA7PYVxPS/ArcGIS/rest/services/CITY_LIMITS_COVID/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("PlanoTXzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services2.arcgis.com/1DyhsVa6rviDKn5t/ArcGIS/rest/services/CCOVID_19_ZIP_Codes_Count/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("CollinTXzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),CollinTXzip051620<-jsonlite::fromJSON("https://services1.arcgis.com/fdWXd5OobWR1E3er/ArcGIS/rest/services/CasesByZip/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("ORzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),ORzip051620<-jsonlite::fromJSON("https://projects.oregonlive.com/coronavirus/data/rona_zip.json")[["features"]][["properties"]])


write.csv(file=paste0("VAzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),read.csv("https://www.vdh.virginia.gov/content/uploads/sites/182/2020/05/VDH-COVID-19-PublicUseDataset-ZIPCode.csv"))

write.csv(file=paste0("WItractsCentroids",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),rbind(jsonlite::fromJSON("https://services1.arcgis.com/ISZ89Z51ft1G16OK/ArcGIS/rest/services/COVID19_WI/FeatureServer/8/query?where=OBJECTID%3E0&objectIds=&resultOffset=&time=RUnit_Meter&outFields=*&returnGeometry=false&returnExceededLimitFeatures=true&f=pjson")[["features"]][["attributes"]],jsonlite::fromJSON("https://services1.arcgis.com/ISZ89Z51ft1G16OK/ArcGIS/rest/services/COVID19_WI/FeatureServer/8/query?where=OBJECTID%3E0&objectIds=&resultOffset=1000&time=&geometry=&resultType=none&distance=0.0&units=esriSRUnit_Meter&outFields=*&returnGeometry=false&returnExceededLimitFeatures=true&f=pjson")[["features"]][["attributes"]]))

write.csv(file=paste0("sfNzip",gsub("[ :]","_",gsub("-","",Sys.time())),jsonlite::fromJSON("https://data.sfgov.org/resource/favi-qct6.json"))

write.csv(file=paste0("SCzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),rbind(jsonlite::fromJSON("https://services2.arcgis.com/XZg2efAbaieYAXmu/ArcGIS/rest/services/COVID19/FeatureServer/1/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]],jsonlite::fromJSON("https://services2.arcgis.com/XZg2efAbaieYAXmu/ArcGIS/rest/services/COVID19/FeatureServer/1/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=1000&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]]))

write.csv(file=paste0("PAzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services2.arcgis.com/xtuWQvb2YQnp0z3F/ArcGIS/rest/services/Zip_Code_COVID19_Case_Data/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&outFields=OBJECTID,PO_NAME,ZIP_CODE,Negative,Positive,Probable,Additional_Tracking,Positive_Redacted,Negative_Redacted&orderByFields=OBJECTID")[["features"]][["attributes"]])

write.csv(file=paste0("MDzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/njFNhDsUCentVYJW/ArcGIS/rest/services/ZIPCodes_MD_1/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&outFields=OBJECTID%2CZIPCODE1%2CZIPName%2CProtectedCount&orderByFields=OBJECTID")[["features"]][["attributes"]]

write.csv(file=paste0("ILzip",gsub("[ :]","_",gsub("-","",Sys.time())),jsonlite::fromJSON("https://www.dph.illinois.gov/sitefiles/COVIDZip.json?nocache=1")[["zip_values"]]))

write.csv(file=paste0("Jeffcozip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services6.arcgis.com/Bd4MACzvEukoZ9mR/ArcGIS/rest/services/JeffcoCasesZip/FeatureServer/1/query?where=FID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("JeffcozipB",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services6.arcgis.com/Bd4MACzvEukoZ9mR/ArcGIS/rest/services/Jefferson_County_Zipcodes_Positive_Covid_19/FeatureServer/0/query?where=FID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("NYCzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/0ZRg6WRC7mxSLyKX/ArcGIS/rest/services/COVID19_NYC_Cases_By_Zip_Code/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=RUnit_Meter&outFields=*&returnGeometry=falseplyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("OmahaNE",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/pDAi2YK0L0QxVJHj/ArcGIS/rest/services/COVID19_Cases_by_ZIP_(View)/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("SarpyCass",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services.arcgis.com/OiG7dbwhQEWoy77N/ArcGIS/rest/services/SarpyCassCOVID_View/FeatureServer/1/query?where=OBJECTID%3E0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("SpokaneCoWAzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),jsonlite::fromJSON("https://services7.arcgis.com/Zrf5IrTQfEv8XhMg/ArcGIS/rest/services/Covid_Cases_by_Zipcode/FeatureServer/0/query?where=FID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]])

write.csv(file=paste0("TravisTXzip",gsub("[ :]","_",gsub("-","",Sys.time())),".csv"),
WashtenawCo051620<-jsonlite::fromJSON("https://services2.arcgis.com/xRI3cTw3hPVoEJP0/ArcGIS/rest/services/Join_COVID_Data_(View)_to_Washtenaw_County_Zip_Codes_(cut)/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=")[["features"]][["attributes"]]
